### PR TITLE
Test docs CI

### PR DESCRIPTION
**Pull request by arnaucasau**
### Summary

Added a test to build the documentation and upload it as part of CI as an artifact for PRs.

### CODE REVIEW

**Comment by arnaucasau** [comment]
Hi @guomanmin, thanks for reviewing the PR! In this pull request, I added a new job into the lint.yml to test the building of the documentation, and the reason we configure pandoc in that job is because it's a requirement for Sphinx. This will be useful in other PRs like [this one](https://github.com/qiskit-community/qiskit-braket-provider/pull/121) where we are updating the ecosystem sphinx theme. As for the version of pandoc it's not a problem in this case :)

**Comment by virajvchaudhari** [comment]
> Hi @guomanmin, thanks for reviewing the PR! In this pull request, I added a new job into the lint.yml to test the building of the documentation, and the reason we configure pandoc in that job is because it's a requirement for Sphinx. This will be useful in other PRs like [this one](https://github.com/qiskit-community/qiskit-braket-provider/pull/121) where we are updating the ecosystem sphinx theme. As for the version of pandoc it's not a problem in this case :)

Hi @arnaucasau, as per the [official sphinx documentation](https://www.sphinx-doc.org/en/master/usage/installation.html), pandoc doesn't seem to be a requirement for sphinx and sphinx-theme. Pandoc seems to be more suitable for document conversion. Can you try checking this without adding this dependency to see if that builds the documentation or this requirement is necessary for anything else?

**Comment by arnaucasau** [comment]
Of course @virajvchaudhari! I tried without adding the dependency and as you can see in the commit the test failed with the error:

> Notebook error:
> PandocMissing in how_tos/0_how_to_access_AWS_Braket_devices.ipynb:
> Pandoc wasn't found.
> Please check that pandoc is installed:
> https://pandoc.org/installing.html

I have added again the package in the last commit.

**Comment by virajvchaudhari** [comment]
I see what's happening there. Thanks for the clarification @arnaucasau!

**Review by virajvchaudhari — APPROVED** [review]

**Comment by arnaucasau** [comment]
Thanks for the approval @virajvchaudhari! Can you merge this PR please? I don't have write access :)

**Pull request merged**
