### PR TITLE
[UnitaryHack] Mock provider, backend

### LINKED ISSUE #19: Tests: mock tests for cloud devices
### What is the expected enhancement?

Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/qiskit-community/qiskit-braket-provider?pullRequest=48) before we can accept your contribution.

Implement mock tests for Braket provider, backend and job for cloud devices.

As a referece for mock end points see https://github.com/aws/amazon-braket-sdk-python/pull/532

### PR DESCRIPTION
**Pull request by WingCode**
### Summary
Mocks backend, provider, job

### Details and comments
closes #19

### CODE REVIEW

**Comment by WingCode** [comment]
@JordanAWS Would could you give me some pointers to look upon for the failing test for [test_real_device_circuit_execution](https://github.com/qiskit-community/qiskit-braket-provider/actions/runs/5225185630/jobs/9434337239?pr=107) ? 
This test-case was previously not being run in CI because the backend, provider wasn't yet mocked and `unittest.skip` was being applied. After mocking the backend, random_circuit transpilation is failing.

**Comment by WingCode** [comment]
After some digging through, I think this test case (failure)[https://github.com/qiskit-community/qiskit-braket-provider/actions/runs/5225185630/jobs/9434337239?pr=107] might be related to this issue #91 since the gates are not supported?

**Comment by kshitijc** [comment]
@WingCode could you try replacing that with a deterministic circuit instead which has supported gates?

**Review by kshitijc — COMMENTED** [review]
Thanks for the updates @WingCode! The issue also calls for adding tests for the backend and job classes.

The coverage for these currently appears to be:

tests/providers/test_adapter.py ....                                     [ 19%]
tests/providers/test_braket_backend.py .....s.sss..                      [ 76%]
tests/providers/test_braket_job.py ..                                    [ 85%]

Would you like to add the tests for backend and job in this PR?

**Comment by WingCode** [comment]
@kshitijc Thank you for the review. Yes, I can add tests for lines not covered in `braket_job.py`, `braket_backend.py` in this PR

**Comment by WingCode** [comment]
@kshitijc Kindly let me know if you like some changes in this PR to get it merged :)

**Comment by WingCode** [comment]
This is how the current coverage looks like :)
image

**Review by kshitijc — APPROVED** [review]
Nice work @WingCode! Thanks for the improved coverage! 👍

**Pull request merged**
