### PR TITLE
Python versions: move from python 3.7 and add support for 3.11

### PR DESCRIPTION
**Pull request by robotAstray**
### Summary:

This PR addresses issue #117 and #119 and enhances the testing capabilities across multiple Python versions, specifically 3.8, 3.9, 3.10, and 3.11.

### Key Changes:

- Modified `.github/workflows/test_latest_versions.yml` to include the following matrix configuration:
```
matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
```

- Modified `./setup.py` to include the following:
```
    classifiers=[
        ....
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Topic :: Scientific/Engineering :: Physics",
    ],
```
and
```
python_requires=">=3.8.2",
```

### CODE REVIEW

**Comment by robotAstray** [comment]
@IceKhan13 I have made the changes for issue 117

**Comment by IceKhan13** [comment]
@robotAstray thank you for this PR! :) 

do not forget about https://github.com/qiskit-community/qiskit-braket-provider/blob/main/setup.py#L42

**Comment by robotAstray** [comment]
@IceKhan13 yes, that's right. I will also add the changes for `setup.py`! Once I am done I will mark the PR "Ready for review"

**Comment by robotAstray** [comment]
I think I made all the necessary changes @IceKhan13, let me know if you need anything else.

**Review by speller26 — APPROVED** [review]

**Pull request merged**
