### PR TITLE
Add ECR gate to mappers

### PR DESCRIPTION
**Pull request by dexter2206**
### Summary

This adds ECR gate to mappers in the `adapters.py` module. Without this addition, running circuits containing the ECR gate through any of the AWS backends is impossible.

### Details and comments

No unit tests were added since there are already tests checking all the mappers. There are also no specific tests for other gates, so I wanted to stay consistent.

### CODE REVIEW

**Review by IceKhan13 — APPROVED** [review]
Sweet! Thank you for this addition @dexter2206 !

**Review by IceKhan13 — CHANGES_REQUESTED** [review]
I think linter is not happy about missing commas at ends of lists :) 

Easy fix will be to run black `black qiskit_braket_provider`

**Comment by dexter2206** [comment]
> I think linter is not happy about missing commas at ends of lists :)
> 
> Easy fix will be to run black `black qiskit_braket_provider`

Ah, sorry, I forgot to run black. Fixed in 9fb5c2a :)

**Review by IceKhan13 — APPROVED** [review]
Sweet! Thank you for contribution 🚀

**Pull request merged**
