### PR TITLE
Rename `AWSBraketJob` to `AmazonBraketTask`

### LINKED ISSUE #45: Rename AWSBraketJob to AmazonBraketTask
https://github.com/qiskit-community/qiskit-braket-provider/blob/1f64aaeceb241df3eb10e696f1e5034e73c1d712/qiskit_braket_provider/providers/braket_job.py#L63

**Make sure that `AWSBraketJob` remains an alias for `AmazonBraketTask`** to avoid breaking existing code.

### PR DESCRIPTION
**Pull request by prakharb10**
### Summary
Closes #45

### Details and comments
I had a couple of questions:
- Should we mark the `AWSBraketJob` class as deprecated?
- Is there a reno required? If yes, then please specify
- I don't have an AWS account/access to Braket service. Is there another way to run the notebooks to reflect the changes?

Thanks

### CODE REVIEW

**Comment by IceKhan13** [comment]
Hey @prakharb10 

> Should we mark the AWSBraketJob class as deprecated?

yes

> Is there a reno required? If yes, then please specify

reno is not required yet

> I don't have an AWS account/access to Braket service. Is there another way to run the notebooks to reflect the changes?

I'm not sure actually. I usually run with cridentials. But this is a good point. Maybe we need to introduce an action, that will rerender notebooks or something like this 🤔 


And also @devilkiller-ag is working on this issue too since he asked for assignment :) It is easier to keep track of who is wokring on what tasks when you have an assignment in github. Can you sync and close this issue together and be co-authors? In true open-source fasion!

**Comment by prakharb10** [comment]
Thanks for the clarification. I'll make the change.

Indeed, I'd be grateful if @ @devilkiller-ag could help with the notebooks.

**Comment by devilkiller-ag** [comment]
@IceKhan13 , @prakharb10  While running the tutorial [0_tutorial_qiskit-braket-provider_overview.ipynb](https://github.com/qiskit-community/qiskit-braket-provider/blob/main/docs/tutorials/0_tutorial_qiskit-braket-provider_overview.ipynb) in docs provider = AWSBraketProvider() is giving error NoRegionError: You must specify a region.. When I pass region as an argument: provider = AWSBraketProvider(region='us-west-2') it's giving error TypeError: AWSBraketProvider() takes no arguments.  Do you have any idea about how to solve this?

**Comment by prakharb10** [comment]
Yeah, I encountered the same error. There are additional steps for running the code outlined here: https://aws.amazon.com/blogs/quantum-computing/introducing-the-qiskit-provider-for-amazon-braket/

Hence, the need for an AWS account

**Comment by devilkiller-ag** [comment]
@Prakharb10 I noticed You Renamed `AWSBraketJob` to `AWSBraketTask`. But it should be `AmazonBraketTask`. I have opened new pull request to rectify it.

**Comment by prakharb10** [comment]
Oh, I see. We can close this if the maintainers decide to go ahead with yours 👍🏻

**Pull request closed without merging**
