### PR TITLE
Add support for verbatim circuits and disable_qubit_rewiring

### PR DESCRIPTION
**Pull request by dexter2206**
### Summary
This PR implements support for verbatim boxes (only for whole circuits) and disabling qubit rewiring. The solution follows exactly the discussion in #58 

### Details and comments
Note that tests for the functionality have a `skip` mark because they necessarily have to access external resources.

### CODE REVIEW

**Review by IceKhan13 — COMMENTED** [review]
@dexter2206 amazing work! All good on code side!

I only have comment on notebook. Last cell is not executed, so, we do not see result. And maybe we should catch error. By that we will show that error is expected. 

What do you think?

**Comment by IceKhan13** [comment]
I think we merge this and fix https://github.com/qiskit-community/qiskit-braket-provider/issues/45 and we will cut new release.

**Comment by dexter2206** [comment]
> @dexter2206 amazing work! All good on code side!
> 
> I only have comment on notebook. Last cell is not executed, so, we do not see result. And maybe we should catch error. By that we will show that error is expected.
> 
> What do you think?

Thanks! I will change the notebook as suggested tomorrow when Aspen is available.

**Comment by IceKhan13** [comment]
@dexter2206 hi there! any updates here? :)

**Review by IceKhan13 — APPROVED** [review]

**Pull request merged**
