### PR TITLE
Migration to Qiskit Primitives 

### PR DESCRIPTION
**Pull request by robotAstray**
### Summary

This PR aim to resolve issue #83.

#### File: `test_braket_backend.py`

Function `test_vqe()`:

- used from `qiskit.algorithms.minimum_eigensolvers import VQE, VQEResult`  (Note: "The old VQE class has been superseded by the [qiskit.algorithms.minimum_eigensolvers.VQE](https://qiskit.org/documentation/locale/ta_IN/stubs/qiskit.algorithms.minimum_eigensolvers.VQE.html#qiskit.algorithms.minimum_eigensolvers.VQE) class.")

- substituted `QuantumInstance` with `BackendEstimator`
- used `estimator` as argument for `VQE` 
- substituted `qiskit.opflow` with `qiskit.quantum_info`
- used `SparsePauliOp` to represent Pauli operators

#### File: `test_adapter.py`

- substituted `qiskit.opflow` with `qiskit.quantum_info`
- used `SparsePauliOp` to represent Pauli operators

#### File: `test_braket_job.py`

_No changes_

#### File: `test_braket_provider.py`

_No changes_

#### File: `docs/tutorials/0_tutorial_qiskit-braket-provider_overview.ipynb`

- used `VQE` from `qiskit.algorithms.minimum_eigensolvers`
- substituted `QuantumInstance` with `BackendEstimator`
- used `SparsePauiliOp` as alternative to `qiskit.opflow` operators

#### File: `docs/tutorials/1_tutorial_vqe.ipynb`

- used `VQE` from `qiskit.algorithms.minimum_eigensolvers`
- substituted `QuantumInstance` with `BackendEstimator`
- used `SparsePauiliOp` as alternative to `qiskit.opflow` operators

#### File: `docs/tutorials/2_tutorial_hybrid_jobs_byoc.ipynb`

- re-run `! cat ./data/2_hybrid_jobs/job_script.py` which displayed the content of the new `job_script.py`

#### File: `docs/tutorials/3_tutorial_minimum_eigen_optimizer.ipynb`

- substituted `QuantumInstance` with `BackendSampler`
- used `COBYLA` to be used as optimiser for `QAOA`
- used `QAOA`, `NumPyMinimumEigensolver` from  new `qiskit.algorithms.minimum_eigensolvers`
- added ```    options={
        "seed_simulator": algorithm_globals.random_seed,
        "seed_transpiler": algorithm_globals.random_seed,
    },``` as options in `BackendSampler()`

#### File: `/data/2_hybrid_jobs/job_script.py`

- used `VQE` from `qiskit.algorithms.minimum_eigensolvers`
- substituted `QuantumInstance` with `BackendEstimator`
- used `SparsePauiliOp` as alternative to `qiskit.opflow` operators

### CODE REVIEW

**Comment by robotAstray** [comment]
@IceKhan13 I have noticed something that might be unrelated to this issue. There is a problem in `test_adaper.py` to be specific function `test_standard_gate_decomp()`. I have made no changes to this function so far, and this error must have been present before this PR started. I will try to resolve the issue as part of this PR
For more info, you can see [here](https://github.com/qiskit-community/qiskit-braket-provider/actions/runs/5756033158/job/15604719407?pr=115)

**Comment by robotAstray** [comment]
@IceKhan13 I have noticed something that might be unrelated to this issue. There is a problem in test_adaper.py to be specific function `test_standard_gate_decomp()`. I have made no changes to this function so far, and this error must have been present before this PR started. I have been working with Python 3.11
For more info, you can see [here](https://github.com/qiskit-community/qiskit-braket-provider/actions/runs/5756033158/job/15604719407?pr=115)

**Comment by robotAstray** [comment]
@IceKhan13 I have noticed something that might be unrelated to this issue. There is a problem in test_adaper.py to be specific function `test_standard_gate_decomp()`. I have made no changes to this function so far, and this error must have been present before this PR started. I have been working with Python 3.11
```
======================================================================
ERROR: test_standard_gate_decomp (test_adapter.TestAdapter.test_standard_gate_decomp)
Tests adapter decomposition of all standard gates to forms that can be translated
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/robotastray/Desktop/github/qiskit-braket-provider/tests/providers/test_adapter.py", line 202, in test_standard_gate_decomp
    qiskit_circuit = qiskit_circuit.assign_parameters(parameter_bindings)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robotastray/Desktop/github/qiskit-braket-provider/venv/lib/python3.11/site-packages/qiskit/circuit/quantumcircuit.py", line 2762, in assign_parameters
    raise CircuitError(
qiskit.circuit.exceptions.CircuitError: 'Cannot bind parameters (0) not present in the circuit.'

----------------------------------------------------------------------
```
For more info, you can see [here](https://github.com/qiskit-community/qiskit-braket-provider/actions/runs/5756033158/job/15604719407?pr=115)

**Comment by robotAstray** [comment]
The error with `test_adapter.py` is due to the following `standard_gates`:
``` 
XXMinusYYGate(Parameter("ϴ")),
 XXPlusYYGate(Parameter("ϴ")),
```
Note this is unrelated to this PR, it something I stumbled upon.
If one comments these gates out of the code there are no issues. I have commented  them out for now. Let me know how you wish to proceed regarding this.

**Comment by IceKhan13** [comment]
Hey @robotAstray ! Thank for this PR!

hmm, something is wrong with this gate specifically. You are right test failing in main branch too https://github.com/qiskit-community/qiskit-braket-provider/actions/runs/5768152751/job/15638813727 and only for python 3.10, but not for 3.7 🤔 

Give me couple of days, I will try to figure out what is going on, so we can remove commented gates from this PR. 

As a heads-up PR looks great! :)

**Comment by IceKhan13** [comment]
@robotAstray fixed failing tests in https://github.com/qiskit-community/qiskit-braket-provider/pull/118. Make sure to merge changes from main, uncomment tests and we can move with PR review!

**Comment by robotAstray** [comment]
Hello @IceKhan13, 
Thank you for your message and help. I have completed the steps now.

**Review by IceKhan13 — APPROVED** [review]
Sweet! 

Thank you @robotAstray !

**Pull request merged**
